name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can specify your preferred Node.js version here

      - name: Install Dependencies and Build
        run: |
          npm install  # Install project dependencies
          npm run build  # Build your site (replace with your actual build command)

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "ctrlbugs"
          git config --global user.email "iamazeeh@gmail.com"

          # Deploy to gh-pages branch
          git checkout gh-pages
          git rm -rf .
          cp -r build/* .
          git add .
          git commit -m "Auto deploy from main branch"
          git push origin gh-pages

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
